INSERT INTO USUARIO (ID, NOMBRE_USUARIO, CONTRASENYA, EMAIL, ENABLED, GRUPO) VALUES (1, 'Administrador', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin@admin.com', 1, '2DAM');
INSERT INTO AUTHORITIES (ID, authority, user_id) VALUES (1, 'ROLE_USER', 1);
INSERT INTO AUTHORITIES (ID, authority, user_id) VALUES (2, 'ROLE_ADMIN', 1);

INSERT INTO USUARIO (ID, NOMBRE_USUARIO, CONTRASENYA, EMAIL, ENABLED, GRUPO) VALUES (2, 'Usuario', '$2a$10$lq6MtokRAo1JnDS7uTNDu.ixrgLAZubZfLMtGkAjfj/xrikKoAL3K', 'usuario@usuario.com', 1, '1DAM');
INSERT INTO AUTHORITIES (ID, authority, user_id) VALUES (3, 'ROLE_USER', 2);

INSERT INTO CAMPANYA (ID, NOMBRE_CAMPANYA, codigo) VALUES (1, 'Campaña del Kilo 2018', 'KILO2018');

INSERT INTO DATOS_MAESTROS (ID, TIPO, CAMPANYA_ID) VALUES (1, 'Aceite', 1);
//INSERT INTO CAMPANYA_DATOS_MAESTROS (CAMPANYA_ID, DATOS_MAESTROS_ID) VALUES (1, 1);